name: CI

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    name: Quality checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run compile

      - name: Run unit tests
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            xvfb-run --auto-servernum npm test
          else
            npm test
          fi

      - name: Package extension artifact
        if: runner.os == 'Linux'
        run: npm run package

      - name: Upload packaged artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: jaenvtix-vsix
          path: dist
          if-no-files-found: error
