name: CI (VS Code Extension)

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [20]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint (ignore if not present)
        run: |
          npm run lint --if-present

      - name: Type check (ignore if not present)
        run: |
          npm run typecheck --if-present

      - name: Build (ignore if not present)
        run: |
          npm run build --if-present

      - name: Unit tests (ignore if not present)
        run: npm test --if-present

      - name: Integration tests (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run -a node .vscode-test.mjs

      - name: Integration tests (macOS/Windows)
        if: runner.os != 'Linux'
        run: node .vscode-test.mjs

      - name: Package VSIX (smoke on Linux)
        if: runner.os == 'Linux'
        run: npx --yes vsce package --no-dependencies

      - name: Upload VSIX artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: extension-vsix
          path: '*.vsix'
